### ISSUE TITLE
Aide pour configuration

### ISSUE THREAD

**Issue by Grognouff** [QuentinCG/jarvis-milight-3.0#2]
Bonjour,

je suis débutant avec jarvis et comme j'ai une lampe Milight avec un wifi ibox V1.0, j'ai donc essayé d'installer ce plugin.
Je regarde le tuto, j'installe, j'utilise Limitless LED pour avoir les informations nécessaires au paramétrage et obtient ceci : 
UDP admin IP : 192.168.1.40
UDP Port : 48899

je paramètre donc de cette façon : 
var_jv_pg_m3_ip="192.168.1.40" # Milight wifi bridge IP
var_jv_pg_m3_port=48899 # Milight wifi bridge port
var_jv_pg_m3_request_timeout_in_sec=5 # Milight wifi bridge communication timeout
var_jv_pg_m3_all_zone_name="maison" # Name of all zone
var_jv_pg_m3_zone_1_name="salon" # Name of the zone 1
var_jv_pg_m3_zone_2_name="wc" # Name of the zone 2
var_jv_pg_m3_zone_3_name="salle de bain" # Name of the zone 3
var_jv_pg_m3_zone_4_name="chambre" # Name of the zone 4

et quand je test, rien ne se passe et j'obtiens:
céline: eteint tout
nestor: Echec de l'extinction des lumières de la zone maison
nestor: Cette commande renvoie une erreur

Qu'est ce que je n'est pas correctement fait, s'il vous plait?

Merci beaucoup

**Comment by QuentinCG** [comment]
Bonsoir,

Je présume que tu arrives à contrôler tes lampes depuis l'appli Android de Milight? (Ou autre contrôleur)

Peux tu essayer la commande "éteins la lumière du module" et "allume la lumière du module"?

Peux tu me donner également le résultat (sur le terminal et si ça a à marché de la commande suivante? (En remplaçant le path vers le bon chemin)... Ça devrait éteindre toute la maison.

```python3 PATH_VERS_LE_PLUGIN/MilightWifiBridge/MilightWifiBridge.py --ip 192.168.1.40 --port 48899 --timeout 5 --zone 0 --setWhiteMode --turnOff```

**Comment by Grognouff** [comment]
Bonsoir,
merci pour la réponse ultra rapide.
Donc,
oui j'ai aucun souci pour commander ma lampe avec mon appli android.

La commande éteint le module me renvoie ceci : 
céline: ETEIN MODULE
nestor: Echec de l'extinction de la lampe du module
nestor: Cette commande renvoie une erreur

la commande dans le terminal me donne ca : 
pi@raspberrypi:~ $ python3 home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge/MilightWifiBridge.py --ip 192.168.1.40 --port 48899 --timeout 5 --zone 0 --setWhiteMode --turnOff
python3: can't open file 'home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge/MilightWifiBridge.py': [Errno 2] No such file or directory
pi@raspberrypi:~ $ 

J'ai essayé aussi avec le chemin home/pi/jarvis/plugins_enabled/.... qui me renvoie la même chose.

Pourtant, je trouve bien le fichier MilightWifiBridge.py avec l'explorateur de fichiers.

Merci

**Comment by QuentinCG** [comment]
Étrange qu'il ne trouve pas le fichier...

Une solution potentielle (si oui, je l'integrerai dans le fichier d'installation):
```sudo apt install dos2unix
dos2unix home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge/MilightWifiBridge.py```

**Comment by Grognouff** [comment]
euh, qu'est ce que je dois en faire?
si je le met dans la console, j'ai ça : 

pi@raspberrypi:~ $ dos2unix home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge/MilightWifiBridge.py```
> 
et c'est tout....  :(

**Comment by QuentinCG** [comment]
Il ne faut pas les 3 ` à la fin.
Après avoir lancé cette commande qui permet de rendre le fichier lisible sur linux, le plugin ne fonctionne toujours pas?

**Comment by Grognouff** [comment]
Merci pour ta patience...

pi@raspberrypi:~ $ dos2unix home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge/MilightWifiBridge.py
bash: dos2unix : commande introuvable
pi@raspberrypi:~ $ sudo apt-get install dos2unix
...
pi@raspberrypi:~ $ dos2unix home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge/MilightWifiBridge.py
dos2unix: home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge/MilightWifiBridge.py: Aucun fichier ou dossier de ce type
dos2unix: Ignore home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge/MilightWifiBridge.py, pas un fichier régulier.

J'ai réessayé le plugin par acquis de conscience, sans succès.

**Comment by QuentinCG** [comment]
Bon... Ton fichier MilightWifiBridge.py semble corrompu.
Deux solutions: 
Soit:  puis installer le plugin 
Soit: faire ces commandes:
```cd home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge
 
rm MilightWifiBridge.py

wget https://raw.githubusercontent.com/QuentinCG/Milight-Wifi-Bridge-3.0-Python-Library/master/MilightWifiBridge/MilightWifiBridge.py
```

**Comment by Grognouff** [comment]
Bonjour,

J'ai réinstallé le plugin et toujours pareil.
Donc je tente la seconde solution : 


en fait dès la première commande ca marche pas : 
pi@raspberrypi:~ $ cd home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge
-bash: cd: home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge: Aucun fichier ou dossier de ce type

Pourtant ca, ca fonctionne : 
pi@raspberrypi:~ $ cd jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge
pi@raspberrypi:~/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge $

et donc si je reprend la commande que tu m'a donné hier:
pi@raspberrypi:~ $ python3 home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge/MilightWifiBridge.py --ip 192.168.1.40 --port 48899 --timeout 5 --zone 0 --setWhiteMode --turnOff
python3: can't open file 'home/pi/jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge/MilightWifiBridge.py': [Errno 2] No such file or directory
pi@raspberrypi:~ $

ca fonctionne pas mais 
pi@raspberrypi:~ $ python3 jarvis/plugins_installed/jarvis-milight-3.0/MilightWifiBridge/MilightWifiBridge.py --ip 192.168.1.40 --port 48899 --timeout 5 --zone 0 --setWhiteMode --turnOff
[ERROR] Request failed
ca fonctionne pas non plus mais c'est pas la même erreur...

**Comment by QuentinCG** [comment]
` [ERROR] Request failed`
Bonne nouvelle: Ca signifie (enfin) que le fichier fonctionne.
Il y a maintenant un problème sur ta configuration.
Je soupçonne le port d'être mauvais. Pourrais tu remettre le port 5987 au lieu de 48899. Il me semble qu'il s'agit du port par défaut (donc si tu n'as pas bidouillé ton ibox, ca devrait être le port 5987).

**Comment by Grognouff** [comment]
j'ai mis le port 5987 et miracle ça fonctionne...
Pourquoi alors Limitless LED me donnait le port 48899?

J'ai un truc bizarre quand même : 
J'ai inversé salon et cuisine dans la paramètres car ma lampe est en zone 1 dans le salon : 
var_jv_pg_m3_all_zone_name="maison" # Name of all zone
var_jv_pg_m3_zone_1_name="salon" # Name of the zone 1
var_jv_pg_m3_zone_2_name="cuisine" # Name of the zone 2
var_jv_pg_m3_zone_3_name="salle de bain" # Name of the zone 3
var_jv_pg_m3_zone_4_name="chambre" # Name of the zone 4	

et j'obtiens : 
Céline: allume cuisine (la llumière s'allume)
nestor: Zone salon allumée
céline: eteint cuisine (la lumière s'éteint)
nestor: Zone salon éteinte
céline: allume salon (il ne se passe rien)
nestor: Zone cuisine allumée

**Comment by QuentinCG** [comment]
Bonne nouvelle !


Pour ton deuxième soucis,
Ca vient peut être de cela (cf REAME du plugin):

```
Configure the configuration file to match your requirements.

Edit the command file if zone is not compatible with those defined in the file
```

Il faut éditer le fichier fr/commands en fonction de tes besoins (change "salon" en "cuisine" et "cuisine" en "salon").
Si c'est fait, revérifie...
Et si tu ne trouve toujours rien, vérifie que le numéro à la fin de chaque ligne correspond à la bonne zone (0 signifiant "tout")

**Comment by Grognouff** [comment]
Merci beaucoup tout fonctionne comme souhaité.
C'est sympa de ta part d'avoir passé du temps à aider un débutant.

**Comment by QuentinCG** [comment]
Pas de soucis :smile:
Ton premier problème était très étrange... Je n'avais encore jamais vu ça...

L'essentiel est que maintenant ça marche et que tu puisse demander à "Nestor" d'allumer et éteindre tes lumières :grinning:
